In [37]:
import numpy as np
import math

# log


In [33]:
# 자연로그 계산
arr = np.array([1, 2, 3, 4, 5])
ln_x = np.log(arr)
print(ln_x)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [40]:
arr = np.array([1, np.e, np.e**2, np.e**3, np.e**4])
ln_x = np.log(arr)
print(ln_x)

[0. 1. 2. 3. 4.]


In [29]:
x = np.array([1, 2, 4, 8, 16])
log2_x = np.log2(x)
print(log2_x)

[0. 1. 2. 3. 4.]


In [24]:
x = np.array([1, 10, 100, 1000, 10000])
log_x = np.log10(x)
print(log_x)


[0. 1. 2. 3. 4.]
